/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/newGallery.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["Animation"].setEffectiveTimeScale(0.5);
    actions["Animation"].play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[7.74, 1.37, 2.55]}
            rotation={[Math.PI, -0.87, Math.PI]}
            scale={0.63}
          >
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
              geometry={nodes.Mesh_22.geometry}
              material={nodes.Mesh_22.material}
              skeleton={nodes.Mesh_22.skeleton}
            />
          </group>
          <group
            position={[7.75, 1.37, -2.59]}
            rotation={[-Math.PI, 0.99, -Math.PI]}
            scale={0.63}
          >
            <primitive object={nodes.GLTF_created_1_rootJoint} />
            <skinnedMesh
              geometry={nodes.Mesh_23.geometry}
              material={nodes.Mesh_23.material}
              skeleton={nodes.Mesh_23.skeleton}
            />
          </group>
          <group position={[-3.23, 0, 4.05]}>
            <mesh
              geometry={nodes.Mesh_0.geometry}
              material={materials.FloorBaked}
            />
          </group>
          <group position={[-3.18, 0, 4.05]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Mesh_1.geometry} material={materials.Glass} />
          </group>
          <group
            position={[-0.07, 1.41, 4.14]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.55}
          >
            <mesh
              geometry={nodes.Mesh_10.geometry}
              material={materials.Image_H_05}
            />
            <mesh
              geometry={nodes.Mesh_11.geometry}
              material={materials.Image_V_04}
            />
            <mesh
              geometry={nodes.Mesh_12.geometry}
              material={materials.Image_H_06}
            />
            <mesh
              geometry={nodes.Mesh_13.geometry}
              material={materials.Image_H_07}
            />
            <mesh
              geometry={nodes.Mesh_14.geometry}
              material={materials.Image_H_08}
            />
            <mesh
              geometry={nodes.Mesh_15.geometry}
              material={materials.Image_V_05}
            />
            <mesh
              geometry={nodes.Mesh_16.geometry}
              material={materials.Image_H_09}
            />
            <mesh
              geometry={nodes.Mesh_2.geometry}
              material={materials.Picture_Frame}
            />
            <mesh
              geometry={nodes.Mesh_3.geometry}
              material={materials.Image_H_01}
            />
            <mesh
              geometry={nodes.Mesh_4.geometry}
              material={materials.Image_V_01}
            />
            <mesh
              geometry={nodes.Mesh_5.geometry}
              material={materials.Image_H_02}
            />
            <mesh
              geometry={nodes.Mesh_6.geometry}
              material={materials.Image_V_02}
            />
            <mesh
              geometry={nodes.Mesh_7.geometry}
              material={materials.Image_H_03}
            />
            <mesh
              geometry={nodes.Mesh_8.geometry}
              material={materials.Image_V_03}
            />
            <mesh
              geometry={nodes.Mesh_9.geometry}
              material={materials.Image_H_04}
            />
          </group>
          <group
            position={[-0.27, 18.92, -5.76]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
          >
            <mesh
              geometry={nodes.Mesh_18.geometry}
              material={materials.material}
            />
          </group>
          <mesh
            geometry={nodes.Mesh_19.geometry}
            material={materials.Terasse_baked}
          />
          <group position={[-3.23, 0, 4.05]} rotation={[0, Math.PI / 2, 0]}>
            <mesh
              geometry={nodes.Mesh_20.geometry}
              material={materials.WallBaked}
            />
          </group>
          <group position={[-3.23, 0, 4.05]}>
            <mesh
              geometry={nodes.Mesh_21.geometry}
              material={materials.WoodBaked}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/newGallery.glb");
